### ISSUE TITLE
error parsing an ACL 

### ISSUE THREAD

**Issue by mjardeli** [GoSecure/Cisco2Checkpoint#12]
Hi Martin,

Sorry to bother you again :)

I am having issues parsing the following config lines:
Can you please help?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
object-group service log_sys udp
 port-object eq syslog
object-group service UDPgroup udp
 group-object log_sys
 port-object eq snmp
 port-object eq echo
 port-object eq domain
 port-object eq ntp
access-list FromInside extended permit udp any4 object-group UDPgroup any4
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error I am getting:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
root@splunk:~/c2c# python2.7 c2c.py --verify --format text --ciscoFile 'test' --syntax asa --policy My_Policy --installOn My_Firewall --output 'network_script_verify.txt'
Traceback (most recent call last):
  File "c2c.py", line 168, in <module>
    c2c.importConfig(args.cpPortsFile,args.cpNetObjFile,args.ciscoFile)
  File "lib/cisco2checkpoint.py", line 1734, in importConfig
    self.parser.parse(configFile, self.syntax)
  File "lib/cisco2checkpoint.py", line 1621, in parse
    self.parse = CiscoConfParse(configFile,factory=True,syntax=syntax)
  File "lib/ciscoconfparse_patch.py", line 1857, in __init__
    CiscoConfParse=self)
  File "lib/ciscoconfparse_patch.py", line 963, in __init__
    ignore_blank_lines, syntax, CiscoConfParse)
  File "/usr/local/lib/python2.7/dist-packages/ciscoconfparse-1.2.40-py2.7.egg/ciscoconfparse/ciscoconfparse.py", line 2598, in __init__
    self._bootstrap_obj_init(data)
  File "/usr/local/lib/python2.7/dist-packages/ciscoconfparse-1.2.40-py2.7.egg/ciscoconfparse/ciscoconfparse.py", line 2755, in _bootstrap_obj_init
    syntax='asa')
  File "lib/ciscoconfparse_patch.py", line 1756, in ConfigLineFactory
    comment_delimiter=comment_delimiter) # instance of the proper subclass
  File "lib/ciscoconfparse_patch.py", line 745, in __init__
    raise ValueError("[FATAL] models_asa cannot parse '{0}'".format(self.text))
ValueError: [FATAL] models_asa cannot parse 'access-list FromInside extended permit udp any4 object-group UDPgroup any4'
root@splunk:~/c2c#
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

thank you,

**Comment by martindube** [comment]
Regarding `object-group UDPgroup`, is it a source port? I am reading the regex and the project do not support source ports yet.

That being said, I would like to ask you if that make sense to import such rules on Checkpoint anyway? :) Are you migrating from a stateless cisco ASA to a stateful checkpoint fw? I personally try to avoid the use of source ports objects in a checkpoint policy.

**Comment by mjardeli** [comment]
Hi Martin,

I am not cisco expert, I agree 100% what you said, make no sense build rules to return packets as checkpoint is stateful. I didnt reconize it on the acl as I am not that good on cisco configs.
Thank you very much for your explanation.

cheers,
